### ISSUE TITLE
Copying text from a cell within a Microsoft Excel Worksheet triggers Textinator

### ISSUE THREAD

**Issue by bwagner** [RhetTbull/textinator#16]
Copying text from a cell within a Microsoft Excel Worksheet triggers Textinator, even though that is already text.

**Comment by RhetTbull** [comment]
I've reproduced this but also verified that Textinator is working "as designed" currently.  Excel copies both a text representation of the cell as well as an image representation of the cell.

<img width="493" alt="Screen Shot 2022-10-25 at 6 35 03 AM" src="https://user-images.githubusercontent.com/41546558/197788372-839a569e-077b-4715-8192-48339a3f1ea3.png">

And here's the image of the cell from the clipboard:

![excel](https://user-images.githubusercontent.com/41546558/197788471-b0c738e1-4150-4475-8d93-351d8c8da0b6.png)

You can disable this by unchecking "Detect text in images on clipboard" and Textinator will ignore the copied cell from Excel.

I'm sure that other apps do this to as macOS allows apps to place multiple representations on the clipboard.  One possible solution is to have Textinator check to see if there is also a text representation on the clipboard and skip it so as not to detect any text. However, it's possible to copy both text and image to the clipboard intentionally, for example, highlight then copy a selection of text and an embedded image in a document. What should Textinator do in this instance?  

I think the most correct behavior is probably to refuse to do text detection if the clipboard contains any text in addition to an image.

**Comment by RhetTbull** [comment]
Fixed in [v0.9.1](https://github.com/RhetTbull/textinator/releases/tag/v0.9.1)

v0.9.1 will look to see if there is also text on the clipboard when an image is copied, and if so, will not run text detection.

**Comment by RhetTbull** [comment]
Still need to add a test case for this condition.
