### ISSUE TITLE
Large portions of text make buttons of dialog "Copy detected text to clipboard?" unreachable

### ISSUE THREAD

**Issue by bwagner** [RhetTbull/textinator#18]
Large portions of text make buttons of dialog "Copy detected text to clipboard?" unreachable (see below). Probably, a scrollable text field should be shown to limit growth of the resulting dialog box.

<img width="587" alt="image" src="https://user-images.githubusercontent.com/447049/212187572-71fb328c-2af7-4114-a145-b6db78493dab.png">

**Comment by RhetTbull** [comment]
Thanks. I'll take a look to see what's possible given the limited UI elements available in RUMPS.

**Comment by bwagner** [comment]
Possibly [rumps.Window](https://rumps.readthedocs.io/en/latest/Window.html)?

**Comment by RhetTbull** [comment]
I've implemented a custom confirmation window that display the detected text in a TextView editable text box. This allows the user to edit it if necessary or copy just part of it. The contents can still be copied to the clipboard with one-click. Will be in the next release.

**Comment by bwagner** [comment]
Awesome! Thanks a lot.

**Comment by RhetTbull** [comment]
Fixed in v0.10.0
