### ISSUE TITLE
Some of Textinator's menu entries don't follow the official Apple Guideline

### ISSUE THREAD

**Issue by bwagner** [RhetTbull/textinator#26]
Some of Textinator's menu entries don't follow the [official Apple Guideline](https://developer.apple.com/design/human-interface-guidelines/the-menu-bar#:~:text=Use%20title%2Dstyle%20capitalization%20if%20you%20need%20to%20use%20more%20than%20one%20word%20in%20the%20menu%20title.): "Use title-style capitalization if you need to use more than one word in the menu title.":
- Text detection confidence threshold -> - Text Detection Confidence Threshold
- Text recognition language -> - Text Recognition Language
- Always detect English -> - Always Detect English
- Detect text in images on clipboard -> - Detect Text in Images on Clipboard
- Pause text detection -> - Pause Text Detection
- Detect QR codes -> - Detect QR Codes
- Keep linebreaks -> - Keep Linebreaks
- Append to clipboard -> - Append to Clipboard
- Clear clipboard -> - Clear Clipboard
- Confirm clipboard changes -> - Confirm Clipboard Changes
- Start Textinator on login -> - Start Textinator on Login

**Comment by RhetTbull** [comment]
Fixed with PR #27 thanks to @bwagner
