### ISSUE TITLE
Textinator only picks up Screenshots at the default location (Desktop) but ignores other locations

### ISSUE THREAD

**Issue by bwagner** [RhetTbull/textinator#29]
Textinator only picks up Screenshots at the default location (Desktop) but ignores other configured locations.

Pressing <kbd>⌘</kbd><kbd>Shift</kbd><kbd>5</kbd> and then Choosing "Options", offers to configure alternative locations to save screen shots to.

However, Textinator ignores these.

**Comment by RhetTbull** [comment]
On my system if Textinator is granted full disk access in Privacy, it does find screenshots in alternate locations. (Ventura)

**Comment by bwagner** [comment]
You're of course right! It'd been a while since I last read the README.

Would it make sense to check for the screenshot location when starting Textinator and remind the user to set the permission when a non-default screenshot location is configured?

Also, on **Sonoma**, the path to configuring is different than what's mentioned in the README:
System Settings...>Privacy & Security>Full Disk Access

README:
System Preferences > Security & Privacy > Full Disk Access

**Comment by RhetTbull** [comment]
> Would it make sense to check for the screenshot location when starting Textinator and remind the user to set the permission when a non-default screenshot location is configured?

Yes. I think that makes sense -- should probably check for access first and if the directory can't be accessed, prompt the user.

**Comment by bwagner** [comment]
I see you merged this pull request, but I'm afraid this one doesn't add anything useful, as custom locations are usable even without this PR.

**Comment by RhetTbull** [comment]
Yes, but I plan to use the code you added to check the screenshot location to add an alert for the user if the location cannot be reached.

**Comment by bwagner** [comment]
ok, thanks!

**Comment by RhetTbull** [comment]
Fixed in v0.10.0
