### ISSUE TITLE
Feature: Pause app

### ISSUE THREAD

**Issue by bwagner** [RhetTbull/textinator#3]
Sometimes you don't want your clipboard affected when taking a screenshot containing text. It would be nice to be able to pause Textinator. Even better: Pause it for a period of time (or, if possible, for the next screenshot).
And/or add a configuration option whether to display a confirm dialog whenever Textinator is about to affect your clipboard.

**Comment by RhetTbull** [comment]
Good suggestion, thanks. I'll add this when I get a chance.

**Comment by RhetTbull** [comment]
@all-contributors please add @bwagner for ideas

**Comment by RhetTbull** [comment]
Added pause/resume in [v0.8.2](https://github.com/RhetTbull/textinator/releases/tag/v0.8.2). Let me know if this doesn't work as expected. When paused, Textinator still receives notifications of new screenshots but does not process them.

**Comment by RhetTbull** [comment]
I implemented this as a simple pause/resume.  If paused, Textinator will not process screenshots until resumed. Textinator will change the status bar icon to one that has “Z”s to indicate snoozing when paused. 

I considered a snooze (for X time or X screenshots) but I don’t want to over complicate the interface which is already getting busy. I’ll think about implementing a “Confirmation” option that would pop up a dialog box showing the detecting text and asking for confirmation to change the clipboard.
